# Generated by Django 4.2 on 2025-11-22 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje_comentario', models.TextField()),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('estado_comentario', models.CharField(choices=[('PUBLICADO', 'Publicado'), ('PENDIENTE', 'Pendiente'), ('RECHAZADO', 'Rechazado')], default='PUBLICADO', max_length=20)),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'db_table': 'COMENTARIO',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_evento', models.CharField(max_length=60)),
                ('descripcion_evento', models.TextField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('lugar', models.CharField(max_length=60)),
                ('tipo_evento', models.CharField(max_length=40)),
                ('cupo', models.IntegerField()),
                ('estado_evento', models.CharField(choices=[('PROGRAMADO', 'Programado'), ('EN_CURSO', 'En Curso'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='PROGRAMADO', max_length=20)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'db_table': 'EVENTO',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id_grupo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_grupo', models.CharField(max_length=60)),
                ('area_interes', models.CharField(max_length=40)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('tipo_grupo', models.CharField(max_length=40)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('correo_grupo', models.EmailField(max_length=128)),
                ('descripcion', models.TextField()),
                ('link_whatsapp', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'db_table': 'GRUPO',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_notificacion', models.CharField(max_length=20)),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'NOTIFICACION',
            },
        ),
        migrations.CreateModel(
            name='Participacion',
            fields=[
                ('id_participaciones', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.CharField(blank=True, max_length=100)),
                ('estado_participacion', models.CharField(choices=[('CONFIRMADO', 'Confirmado'), ('PENDIENTE', 'Pendiente'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='grupos.evento')),
            ],
            options={
                'verbose_name': 'Participación',
                'verbose_name_plural': 'Participaciones',
                'db_table': 'PARTICIPACION',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('MODERADOR', 'Moderador'), ('MIEMBRO', 'Miembro'), ('INVITADO', 'Invitado')], default='MIEMBRO', max_length=20)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'ROL',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('correo_usuario', models.EmailField(max_length=128, unique=True)),
                ('estado_usuario', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('SUSPENDIDO', 'Suspendido')], default='ACTIVO', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'USUARIO',
            },
        ),
        migrations.CreateModel(
            name='UsuarioNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leida', models.BooleanField(default=False)),
                ('notificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupos.notificacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupos.usuario')),
            ],
            options={
                'db_table': 'USUARIO_NOTIFICACION',
                'unique_together': {('usuario', 'notificacion')},
            },
        ),
        migrations.CreateModel(
            name='UsuarioGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_union', models.DateTimeField(auto_now_add=True)),
                ('rol_en_grupo', models.CharField(choices=[('ADMIN', 'Administrador'), ('MIEMBRO', 'Miembro')], default='MIEMBRO', max_length=20)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupos.grupo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupos.usuario')),
            ],
            options={
                'db_table': 'USUARIO_GRUPO',
                'unique_together': {('usuario', 'grupo')},
            },
        ),
        migrations.CreateModel(
            name='UsuarioComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupos.comentario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupos.usuario')),
            ],
            options={
                'db_table': 'USUARIO_COMENTARIO',
                'unique_together': {('usuario', 'comentario')},
            },
        ),
        migrations.CreateModel(
            name='ParticipacionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupos.participacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupos.usuario')),
            ],
            options={
                'db_table': 'PARTICIPACION_USUARIO',
                'unique_together': {('usuario', 'participacion')},
            },
        ),
        migrations.AddField(
            model_name='participacion',
            name='usuarios',
            field=models.ManyToManyField(related_name='participaciones', through='grupos.ParticipacionUsuario', to='grupos.usuario'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='usuarios',
            field=models.ManyToManyField(related_name='notificaciones', through='grupos.UsuarioNotificacion', to='grupos.usuario'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='miembros',
            field=models.ManyToManyField(related_name='grupos', through='grupos.UsuarioGrupo', to='grupos.usuario'),
        ),
        migrations.AddField(
            model_name='evento',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='grupos.grupo'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='usuarios',
            field=models.ManyToManyField(related_name='comentarios', through='grupos.UsuarioComentario', to='grupos.usuario'),
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupos.rol')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupos.usuario')),
            ],
            options={
                'db_table': 'USUARIO_ROL',
                'unique_together': {('usuario', 'rol')},
            },
        ),
    ]
