# Generated by Django 4.2.7 on 2025-11-28 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_creados', to='grupos.usuario'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='estado_grupo',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='grupo',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rol',
            name='nombre_rol',
            field=models.CharField(choices=[('ADMIN_GENERAL', 'Administrador General'), ('ADMIN_CLUB', 'Administrador de Club'), ('ESTUDIANTE', 'Estudiante'), ('ADMIN', 'Administrador (legacy)'), ('MODERADOR', 'Moderador (legacy)'), ('MIEMBRO', 'Miembro (legacy)'), ('INVITADO', 'Invitado (legacy)')], default='ESTUDIANTE', max_length=20),
        ),
    ]
