# Generated by Django 4.2.7 on 2025-11-28 15:09

from django.db import migrations, models, transaction
import django.db.models.deletion


def create_default_roles(apps, schema_editor):
    Rol = apps.get_model("grupos", "Rol")
    defaults = [
        ("ADMIN_GENERAL", "Administrador General"),
        ("ADMIN_CLUB", "Administrador de Club"),
        ("ESTUDIANTE", "Estudiante"),
    ]
    with transaction.atomic():
        for name, label in defaults:
            Rol.objects.get_or_create(nombre_rol=name, defaults={"descripcion": label})


class Migration(migrations.Migration):

    dependencies = [
        ("grupos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="grupo",
            name="aprobado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="grupos_aprobados",
                to="grupos.usuario",
            ),
        ),
        migrations.AddField(
            model_name="grupo",
            name="comentario_revision",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="grupo",
            name="estado_validacion",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "Pendiente de aprobación"),
                    ("APROBADO", "Aprobado"),
                    ("RECHAZADO", "Rechazado"),
                ],
                default="PENDIENTE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="grupo",
            name="solicitante",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="grupos_solicitados",
                to="grupos.usuario",
            ),
        ),
        migrations.AddField(
            model_name="rol",
            name="descripcion",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="rol",
            name="nombre_rol",
            field=models.CharField(
                choices=[
                    ("ADMIN_GENERAL", "Administrador General"),
                    ("ADMIN_CLUB", "Administrador de Club"),
                    ("ESTUDIANTE", "Estudiante"),
                ],
                default="ESTUDIANTE",
                max_length=20,
            ),
        ),
        migrations.RunPython(create_default_roles, migrations.RunPython.noop),
    ]
