# Generated by Django 4.2.7 on 2025-11-30 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0002_grupo_aprobado_por_grupo_comentario_revision_and_more'),
        ('grupos', '0003_merge_20251201_0000'),
    ]

    operations = [
    ]
