-- Elimina todas las tablas si existen
DROP TABLE IF EXISTS USUARIO_ROL;
DROP TABLE IF EXISTS USUARIO_NOTIFICACION;
DROP TABLE IF EXISTS USUARIO_GRUPO;
DROP TABLE IF EXISTS USUARIO_COMENTARIO;
DROP TABLE IF EXISTS PARTICIPACION_USUARIO;
DROP TABLE IF EXISTS EVENTO;
DROP TABLE IF EXISTS COMENTARIO;
DROP TABLE IF EXISTS NOTIFICACION;
DROP TABLE IF EXISTS PARTICIPACION;
DROP TABLE IF EXISTS ROL;
DROP TABLE IF EXISTS USUARIO;
DROP TABLE IF EXISTS GRUPO;

-- Tabla: GRUPO
CREATE TABLE GRUPO (
    ID_GRUPO INT NOT NULL PRIMARY KEY,
    NOMBRE_GRUPO VARCHAR(60) NOT NULL,
    AREA_INTERES VARCHAR(40) NOT NULL,
    FECHA_CREACION DATE NOT NULL,
    TIPO_GRUPO VARCHAR(40) NOT NULL,
    LOGO LONGBLOB NULL,
    CORREO_GRUPO VARCHAR(128) NOT NULL,
    DESCRIPCION TEXT NOT NULL,
    LINK_WHATSAPP VARCHAR(128) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabla: USUARIO
CREATE TABLE USUARIO (
    ID_USUARIO INT NOT NULL PRIMARY KEY,
    NOMBRE_USUARIO VARCHAR(60) NOT NULL,
    APELLIDO VARCHAR(60) NOT NULL,
    CORREO_USUARIO VARCHAR(128) NOT NULL,
    ESTADO_USUARIO VARCHAR(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabla: ROL
CREATE TABLE ROL (
    ID_ROL INT NOT NULL PRIMARY KEY,
    NOMBRE_ROL VARCHAR(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabla: COMENTARIO
CREATE TABLE COMENTARIO (
    ID_COMENTARIO INT NOT NULL PRIMARY KEY,
    MENSAJE_COMENTARIO TEXT NOT NULL,
    FECHA_PUBLICACION DATE NOT NULL,
    ESTADO_COMENTARIO VARCHAR(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabla: NOTIFICACION
CREATE TABLE NOTIFICACION (
    ID_NOTIFICACION INT NOT NULL PRIMARY KEY,
    TIPO_NOTIFICACION VARCHAR(20) NOT NULL,
    MENSAJE TEXT NOT NULL,
    FECHA_ENVIO DATE NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabla: PARTICIPACION
CREATE TABLE PARTICIPACION (
    ID_PARTICIPACIONES INT NOT NULL PRIMARY KEY,
    FECHA_REGISTRO DATE NOT NULL,
    COMENTARIO VARCHAR(100) NOT NULL,
    ESTADO_PARTICIPACION VARCHAR(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabla: EVENTO
CREATE TABLE EVENTO (
    ID_EVENTO INT NOT NULL PRIMARY KEY,
    ID_GRUPO INT NOT NULL,
    NOMBRE_EVENTO VARCHAR(60) NOT NULL,
    DESCRIPCION_EVENTO TEXT NOT NULL,
    FECHA_INICIO DATE NOT NULL,
    FECHA_FIN DATE NOT NULL,
    LUGAR VARCHAR(60) NOT NULL,
    TIPO_EVENTO VARCHAR(40) NOT NULL,
    CUPO VARCHAR(20) NOT NULL,
    ESTADO_EVENTO VARCHAR(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX GRUPO_EVENTO_FK ON EVENTO (ID_GRUPO);

-- Tabla: PARTICIPACION_USUARIO
CREATE TABLE PARTICIPACION_USUARIO (
    ID_USUARIO INT NOT NULL,
    ID_PARTICIPACIONES INT NOT NULL,
    PRIMARY KEY (ID_USUARIO, ID_PARTICIPACIONES)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX PARTICIPACION_USUARIO2_FK ON PARTICIPACION_USUARIO (ID_PARTICIPACIONES);
CREATE INDEX PARTICIPACION_USUARIO_FK ON PARTICIPACION_USUARIO (ID_USUARIO);

-- Tabla: USUARIO_COMENTARIO
CREATE TABLE USUARIO_COMENTARIO (
    ID_COMENTARIO INT NOT NULL,
    ID_USUARIO INT NOT NULL,
    PRIMARY KEY (ID_COMENTARIO, ID_USUARIO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX USUARIO_COMENTARIO2_FK ON USUARIO_COMENTARIO (ID_USUARIO);
CREATE INDEX USUARIO_COMENTARIO_FK ON USUARIO_COMENTARIO (ID_COMENTARIO);

-- Tabla: USUARIO_GRUPO
CREATE TABLE USUARIO_GRUPO (
    ID_GRUPO INT NOT NULL,
    ID_USUARIO INT NOT NULL,
    PRIMARY KEY (ID_GRUPO, ID_USUARIO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX USUARIO_GRUPO2_FK ON USUARIO_GRUPO (ID_USUARIO);
CREATE INDEX USUARIO_GRUPO_FK ON USUARIO_GRUPO (ID_GRUPO);

-- Tabla: USUARIO_NOTIFICACION
CREATE TABLE USUARIO_NOTIFICACION (
    ID_NOTIFICACION INT NOT NULL,
    ID_USUARIO INT NOT NULL,
    PRIMARY KEY (ID_NOTIFICACION, ID_USUARIO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX USUARIO_NOTIFICACION2_FK ON USUARIO_NOTIFICACION (ID_USUARIO);
CREATE INDEX USUARIO_NOTIFICACION_FK ON USUARIO_NOTIFICACION (ID_NOTIFICACION);

-- Tabla: USUARIO_ROL
CREATE TABLE USUARIO_ROL (
    ID_ROL INT NOT NULL,
    ID_USUARIO INT NOT NULL,
    PRIMARY KEY (ID_ROL, ID_USUARIO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX USUARIO_ROL2_FK ON USUARIO_ROL (ID_USUARIO);
CREATE INDEX USUARIO_ROL_FK ON USUARIO_ROL (ID_ROL);

-- Foreign Keys
ALTER TABLE EVENTO
    ADD CONSTRAINT FK_EVENTO_GRUPO_EVE_GRUPO FOREIGN KEY (ID_GRUPO)
        REFERENCES GRUPO (ID_GRUPO);

ALTER TABLE PARTICIPACION_USUARIO
    ADD CONSTRAINT FK_PARTICIP_PARTICIPA_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES USUARIO (ID_USUARIO);
ALTER TABLE PARTICIPACION_USUARIO
    ADD CONSTRAINT FK_PARTICIP_PARTICIPA_PARTICIP FOREIGN KEY (ID_PARTICIPACIONES)
        REFERENCES PARTICIPACION (ID_PARTICIPACIONES);

ALTER TABLE USUARIO_COMENTARIO
    ADD CONSTRAINT FK_USUARIO__USUARIO_C_COMENTAR FOREIGN KEY (ID_COMENTARIO)
        REFERENCES COMENTARIO (ID_COMENTARIO);
ALTER TABLE USUARIO_COMENTARIO
    ADD CONSTRAINT FK_USUARIO__USUARIO_C_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES USUARIO (ID_USUARIO);

ALTER TABLE USUARIO_GRUPO
    ADD CONSTRAINT FK_USUARIO__USUARIO_G_GRUPO FOREIGN KEY (ID_GRUPO)
        REFERENCES GRUPO (ID_GRUPO);
ALTER TABLE USUARIO_GRUPO
    ADD CONSTRAINT FK_USUARIO__USUARIO_G_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES USUARIO (ID_USUARIO);

ALTER TABLE USUARIO_NOTIFICACION
    ADD CONSTRAINT FK_USUARIO__USUARIO_N_NOTIFICA FOREIGN KEY (ID_NOTIFICACION)
        REFERENCES NOTIFICACION (ID_NOTIFICACION);
ALTER TABLE USUARIO_NOTIFICACION
    ADD CONSTRAINT FK_USUARIO__USUARIO_N_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES USUARIO (ID_USUARIO);

ALTER TABLE USUARIO_ROL
    ADD CONSTRAINT FK_USUARIO__USUARIO_R_ROL FOREIGN KEY (ID_ROL)
        REFERENCES ROL (ID_ROL);
ALTER TABLE USUARIO_ROL
    ADD CONSTRAINT FK_USUARIO__USUARIO_R_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES USUARIO (ID_USUARIO);

-- Datos de ejemplo
INSERT INTO GRUPO (ID_GRUPO, NOMBRE_GRUPO, AREA_INTERES, FECHA_CREACION, TIPO_GRUPO, LOGO, CORREO_GRUPO, DESCRIPCION, LINK_WHATSAPP)
VALUES (1, 'Club de Desarrollo Web UNAL', 'Tecnología', CURDATE(), 'Semillero', NULL, 'club.web@unal.edu.co', 'Club oficial de desarrollo web de la UNAL', NULL);

INSERT INTO GRUPO (ID_GRUPO, NOMBRE_GRUPO, AREA_INTERES, FECHA_CREACION, TIPO_GRUPO, LOGO, CORREO_GRUPO, DESCRIPCION, LINK_WHATSAPP)
VALUES (2, 'Grupo de Investigación IA', 'Ciencias', CURDATE(), 'Investigación', NULL, 'ia.lab@unal.edu.co', 'Laboratorio de Inteligencia Artificial', NULL);

INSERT INTO USUARIO (ID_USUARIO, NOMBRE_USUARIO, APELLIDO, CORREO_USUARIO, ESTADO_USUARIO)
VALUES (1, 'Juan', 'Pérez', 'juan.perez@unal.edu.co', 'Activo');
INSERT INTO USUARIO (ID_USUARIO, NOMBRE_USUARIO, APELLIDO, CORREO_USUARIO, ESTADO_USUARIO)
VALUES (2, 'María', 'Gómez', 'maria.gomez@unal.edu.co', 'Activo');
